# Un ensemble de gems et fichiers pour séparer mon travail
gem 'soap4r-ruby1.9'
gem 'logger-application'
require 'biblio'
require 'menus'
require 'test'
require 'logger'
require 'logger-application'
require 'soap/rpc/standaloneServer'
require 'soap/rpc/driver'